console.log "'Allo from CoffeeScript!"
console.log "'Allo from CoffeeScript!"
console.log "'Allo from CoffeeScript!"
console.log "'Allo from CoffeeScript!"
console.log "'Allo from CoffeeScript!"
console.log "'Allo from CoffeeScript!"
console.log "'Allo from CoffeeScript!"
